# Generated by Django 5.2.5 on 2025-09-05 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_item_sale'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
